onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma

overrides:
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  qs@<6.14.1: '>=6.14.1'
  validator@<13.15.22: '>=13.15.22'
